---
- name: install ntp server
  apt: 
    name: ['ntpsec']
    state: latest
  tags:
    - install_ntp
    - install

- import_tasks: configure.yml
  tags:
    - configure_ntp
    - configure
    - ntp
